name: Deploy-Docsify

on:
  push:
    branches:
      - doc

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ssh connect server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # ip address
          username: ${{ secrets.SSH_USER }} # server username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # server ssh private key

      - name: Run Script to Deploy serve
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          BLOG_PATH_REMOTE: ${{ secrets.BLOG_PATH_REMOTE }}
          APP_NAME: docsify-blog
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
          ssh $SSH_USER@$SSH_HOST  << EOF
          cd $BLOG_PATH_REMOTE
          # 设置重试次数和计数器
          MAX_RETRIES=10
          RETRY_COUNT=0

          # 循环尝试拉取代码
          while [ \$RETRY_COUNT -lt \$MAX_RETRIES ]; do
            if git pull origin doc; then
              break  # 如果成功拉取，则跳出循环
            else
              echo "Git pull failed, retrying (\$((RETRY_COUNT + 1)) of \$MAX_RETRIES)..."
              ((RETRY_COUNT++))
              sleep 5  # 等待5秒后重试
            fi
          done

          # 检查是否达到了最大重试次数
          if [ \$RETRY_COUNT -eq \$MAX_RETRIES ]; then
            echo "Failed to pull code after \$MAX_RETRIES attempts. Exiting."
            exit 1  # 抛出异常并退出进程
          fi

          pm2 restart $APP_NAME || pm2 start "docsify s" --name $APP_NAME
          EOF
